// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Config Connector and manual
//     changes will be clobbered when the file is regenerated.
//
// ----------------------------------------------------------------------------

// *** DISCLAIMER ***
// Config Connector's go-client for CRDs is currently in ALPHA, which means
// that future versions of the go-client may include breaking changes.
// Please try it out and give us feedback!

package v1beta1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/clients/generated/apis/k8s/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type UrlmapAbort struct {
	
	// +optional
	HttpStatus *int64 `json:"httpStatus,omitempty"`

	
	// +optional
	Percentage *float64 `json:"percentage,omitempty"`
}

type UrlmapCorsPolicy struct {
	
	// +optional
	AllowCredentials *bool `json:"allowCredentials,omitempty"`

	
	// +optional
	AllowHeaders []string `json:"allowHeaders,omitempty"`

	
	// +optional
	AllowMethods []string `json:"allowMethods,omitempty"`

	
	// +optional
	AllowOriginRegexes []string `json:"allowOriginRegexes,omitempty"`

	
	// +optional
	AllowOrigins []string `json:"allowOrigins,omitempty"`

	
	// +optional
	Disabled *bool `json:"disabled,omitempty"`

	
	// +optional
	ExposeHeaders []string `json:"exposeHeaders,omitempty"`

	
	// +optional
	MaxAge *int64 `json:"maxAge,omitempty"`
}

type UrlmapDefaultRouteAction struct {
	
	// +optional
	CorsPolicy *UrlmapCorsPolicy `json:"corsPolicy,omitempty"`

	
	// +optional
	FaultInjectionPolicy *UrlmapFaultInjectionPolicy `json:"faultInjectionPolicy,omitempty"`

	
	// +optional
	RequestMirrorPolicy *UrlmapRequestMirrorPolicy `json:"requestMirrorPolicy,omitempty"`

	
	// +optional
	RetryPolicy *UrlmapRetryPolicy `json:"retryPolicy,omitempty"`

	
	// +optional
	Timeout *UrlmapTimeout `json:"timeout,omitempty"`

	
	// +optional
	UrlRewrite *UrlmapUrlRewrite `json:"urlRewrite,omitempty"`

	
	// +optional
	WeightedBackendServices []UrlmapWeightedBackendServices `json:"weightedBackendServices,omitempty"`
}

type UrlmapDefaultService struct {
	// +optional
	BackendBucketRef *v1alpha1.ResourceRef `json:"backendBucketRef,omitempty"`

	// +optional
	BackendServiceRef *v1alpha1.ResourceRef `json:"backendServiceRef,omitempty"`
}

type UrlmapDefaultUrlRedirect struct {
	
	// +optional
	HostRedirect *string `json:"hostRedirect,omitempty"`

	
	// +optional
	HttpsRedirect *bool `json:"httpsRedirect,omitempty"`

	
	// +optional
	PathRedirect *string `json:"pathRedirect,omitempty"`

	
	// +optional
	PrefixRedirect *string `json:"prefixRedirect,omitempty"`

	
	// +optional
	RedirectResponseCode *string `json:"redirectResponseCode,omitempty"`

	
	StripQuery bool `json:"stripQuery"`
}

type UrlmapDelay struct {
	
	// +optional
	FixedDelay *UrlmapFixedDelay `json:"fixedDelay,omitempty"`

	
	// +optional
	Percentage *float64 `json:"percentage,omitempty"`
}

type UrlmapFaultInjectionPolicy struct {
	
	// +optional
	Abort *UrlmapAbort `json:"abort,omitempty"`

	
	// +optional
	Delay *UrlmapDelay `json:"delay,omitempty"`
}

type UrlmapFilterLabels struct {
	
	Name string `json:"name"`

	
	Value string `json:"value"`
}

type UrlmapFixedDelay struct {
	
	// +optional
	Nanos *int64 `json:"nanos,omitempty"`

	
	Seconds string `json:"seconds"`
}

type UrlmapHeaderAction struct {
	
	// +optional
	RequestHeadersToAdd []UrlmapRequestHeadersToAdd `json:"requestHeadersToAdd,omitempty"`

	
	// +optional
	RequestHeadersToRemove []string `json:"requestHeadersToRemove,omitempty"`

	
	// +optional
	ResponseHeadersToAdd []UrlmapResponseHeadersToAdd `json:"responseHeadersToAdd,omitempty"`

	
	// +optional
	ResponseHeadersToRemove []string `json:"responseHeadersToRemove,omitempty"`
}

type UrlmapHeaderMatches struct {
	
	// +optional
	ExactMatch *string `json:"exactMatch,omitempty"`

	
	HeaderName string `json:"headerName"`

	
	// +optional
	InvertMatch *bool `json:"invertMatch,omitempty"`

	
	// +optional
	PrefixMatch *string `json:"prefixMatch,omitempty"`

	
	// +optional
	PresentMatch *bool `json:"presentMatch,omitempty"`

	
	// +optional
	RangeMatch *UrlmapRangeMatch `json:"rangeMatch,omitempty"`

	
	// +optional
	RegexMatch *string `json:"regexMatch,omitempty"`

	
	// +optional
	SuffixMatch *string `json:"suffixMatch,omitempty"`
}

type UrlmapHostRule struct {
	
	// +optional
	Description *string `json:"description,omitempty"`

	
	Hosts []string `json:"hosts"`

	
	PathMatcher string `json:"pathMatcher"`
}

type UrlmapMatchRules struct {
	
	// +optional
	FullPathMatch *string `json:"fullPathMatch,omitempty"`

	
	// +optional
	HeaderMatches []UrlmapHeaderMatches `json:"headerMatches,omitempty"`

	
	// +optional
	IgnoreCase *bool `json:"ignoreCase,omitempty"`

	
	// +optional
	MetadataFilters []UrlmapMetadataFilters `json:"metadataFilters,omitempty"`

	
	// +optional
	PathTemplateMatch *string `json:"pathTemplateMatch,omitempty"`

	
	// +optional
	PrefixMatch *string `json:"prefixMatch,omitempty"`

	
	// +optional
	QueryParameterMatches []UrlmapQueryParameterMatches `json:"queryParameterMatches,omitempty"`

	
	// +optional
	RegexMatch *string `json:"regexMatch,omitempty"`
}

type UrlmapMetadataFilters struct {
	
	FilterLabels []UrlmapFilterLabels `json:"filterLabels"`

	
	FilterMatchCriteria string `json:"filterMatchCriteria"`
}

type UrlmapPathMatcher struct {
	
	// +optional
	DefaultRouteAction *UrlmapDefaultRouteAction `json:"defaultRouteAction,omitempty"`

	
	// +optional
	DefaultService *UrlmapDefaultService `json:"defaultService,omitempty"`

	
	// +optional
	DefaultUrlRedirect *UrlmapDefaultUrlRedirect `json:"defaultUrlRedirect,omitempty"`

	
	// +optional
	Description *string `json:"description,omitempty"`

	
	// +optional
	HeaderAction *UrlmapHeaderAction `json:"headerAction,omitempty"`

	
	Name string `json:"name"`

	
	// +optional
	PathRule []UrlmapPathRule `json:"pathRule,omitempty"`

	
	// +optional
	RouteRules []UrlmapRouteRules `json:"routeRules,omitempty"`
}

type UrlmapPathRule struct {
	
	Paths []string `json:"paths"`

	
	// +optional
	RouteAction *UrlmapRouteAction `json:"routeAction,omitempty"`

	
	// +optional
	Service *UrlmapService `json:"service,omitempty"`

	
	// +optional
	UrlRedirect *UrlmapUrlRedirect `json:"urlRedirect,omitempty"`
}

type UrlmapPerTryTimeout struct {
	
	// +optional
	Nanos *int64 `json:"nanos,omitempty"`

	
	Seconds string `json:"seconds"`
}

type UrlmapQueryParameterMatches struct {
	
	// +optional
	ExactMatch *string `json:"exactMatch,omitempty"`

	
	Name string `json:"name"`

	
	// +optional
	PresentMatch *bool `json:"presentMatch,omitempty"`

	
	// +optional
	RegexMatch *string `json:"regexMatch,omitempty"`
}

type UrlmapRangeMatch struct {
	
	RangeEnd int64 `json:"rangeEnd"`

	
	RangeStart int64 `json:"rangeStart"`
}

type UrlmapRequestHeadersToAdd struct {
	
	HeaderName string `json:"headerName"`

	
	HeaderValue string `json:"headerValue"`

	
	Replace bool `json:"replace"`
}

type UrlmapRequestMirrorPolicy struct {
	
	BackendServiceRef v1alpha1.ResourceRef `json:"backendServiceRef"`
}

type UrlmapResponseHeadersToAdd struct {
	
	HeaderName string `json:"headerName"`

	
	HeaderValue string `json:"headerValue"`

	
	Replace bool `json:"replace"`
}

type UrlmapRetryPolicy struct {
	
	NumRetries int64 `json:"numRetries"`

	
	// +optional
	PerTryTimeout *UrlmapPerTryTimeout `json:"perTryTimeout,omitempty"`

	
	// +optional
	RetryConditions []string `json:"retryConditions,omitempty"`
}

type UrlmapRouteAction struct {
	
	// +optional
	CorsPolicy *UrlmapCorsPolicy `json:"corsPolicy,omitempty"`

	
	// +optional
	FaultInjectionPolicy *UrlmapFaultInjectionPolicy `json:"faultInjectionPolicy,omitempty"`

	
	// +optional
	RequestMirrorPolicy *UrlmapRequestMirrorPolicy `json:"requestMirrorPolicy,omitempty"`

	
	// +optional
	RetryPolicy *UrlmapRetryPolicy `json:"retryPolicy,omitempty"`

	
	// +optional
	Timeout *UrlmapTimeout `json:"timeout,omitempty"`

	
	// +optional
	UrlRewrite *UrlmapUrlRewrite `json:"urlRewrite,omitempty"`

	
	// +optional
	WeightedBackendServices []UrlmapWeightedBackendServices `json:"weightedBackendServices,omitempty"`
}

type UrlmapRouteRules struct {
	
	// +optional
	HeaderAction *UrlmapHeaderAction `json:"headerAction,omitempty"`

	
	// +optional
	MatchRules []UrlmapMatchRules `json:"matchRules,omitempty"`

	
	Priority int64 `json:"priority"`

	
	// +optional
	RouteAction *UrlmapRouteAction `json:"routeAction,omitempty"`

	
	// +optional
	Service *string `json:"service,omitempty"`

	
	// +optional
	UrlRedirect *UrlmapUrlRedirect `json:"urlRedirect,omitempty"`
}

type UrlmapService struct {
	// +optional
	BackendBucketRef *v1alpha1.ResourceRef `json:"backendBucketRef,omitempty"`

	// +optional
	BackendServiceRef *v1alpha1.ResourceRef `json:"backendServiceRef,omitempty"`
}

type UrlmapTest struct {
	
	// +optional
	Description *string `json:"description,omitempty"`

	
	Host string `json:"host"`

	
	Path string `json:"path"`

	
	Service UrlmapService `json:"service"`
}

type UrlmapTimeout struct {
	
	// +optional
	Nanos *int64 `json:"nanos,omitempty"`

	
	Seconds string `json:"seconds"`
}

type UrlmapUrlRedirect struct {
	
	// +optional
	HostRedirect *string `json:"hostRedirect,omitempty"`

	
	// +optional
	HttpsRedirect *bool `json:"httpsRedirect,omitempty"`

	
	// +optional
	PathRedirect *string `json:"pathRedirect,omitempty"`

	
	// +optional
	PrefixRedirect *string `json:"prefixRedirect,omitempty"`

	
	// +optional
	RedirectResponseCode *string `json:"redirectResponseCode,omitempty"`

	
	// +optional
	StripQuery *bool `json:"stripQuery,omitempty"`
}

type UrlmapUrlRewrite struct {
	
	// +optional
	HostRewrite *string `json:"hostRewrite,omitempty"`

	
	// +optional
	PathPrefixRewrite *string `json:"pathPrefixRewrite,omitempty"`

	
	// +optional
	PathTemplateRewrite *string `json:"pathTemplateRewrite,omitempty"`
}

type UrlmapWeightedBackendServices struct {
	
	BackendServiceRef v1alpha1.ResourceRef `json:"backendServiceRef"`

	
	// +optional
	HeaderAction *UrlmapHeaderAction `json:"headerAction,omitempty"`

	
	Weight int64 `json:"weight"`
}

type ComputeURLMapSpec struct {
	
	// +optional
	DefaultRouteAction *UrlmapDefaultRouteAction `json:"defaultRouteAction,omitempty"`

	
	// +optional
	DefaultService *UrlmapDefaultService `json:"defaultService,omitempty"`

	
	// +optional
	DefaultUrlRedirect *UrlmapDefaultUrlRedirect `json:"defaultUrlRedirect,omitempty"`

	
	// +optional
	Description *string `json:"description,omitempty"`

	
	// +optional
	HeaderAction *UrlmapHeaderAction `json:"headerAction,omitempty"`

	
	// +optional
	HostRule []UrlmapHostRule `json:"hostRule,omitempty"`

	
	Location string `json:"location"`

	
	// +optional
	PathMatcher []UrlmapPathMatcher `json:"pathMatcher,omitempty"`

	
	// +optional
	ResourceID *string `json:"resourceID,omitempty"`

	
	// +optional
	Test []UrlmapTest `json:"test,omitempty"`
}

type ComputeURLMapStatus struct {
	
	Conditions []v1alpha1.Condition `json:"conditions,omitempty"`
	
	// +optional
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`

	
	// +optional
	Fingerprint *string `json:"fingerprint,omitempty"`

	
	// +optional
	MapId *int64 `json:"mapId,omitempty"`

	
	// +optional
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// +optional
	ExternalRef *string `json:"externalRef,omitempty"`

	// +optional
	ObservedState *ComputeURLMapObservedState `json:"observedState,omitempty"`

	// +optional
	SelfLink *string `json:"selfLink,omitempty"`
}

// +kcc:observedstate:proto=google.cloud.compute.v1.UrlMap
type ComputeURLMapObservedState struct {
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:categories=gcp,shortName=gcpcomputeurlmap;gcpcomputeurlmaps
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/managed-by-kcc=true"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/stability-level=stable"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/system=true"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/tf2crd=true"
// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type="date"
// +kubebuilder:printcolumn:name="Ready",JSONPath=".status.conditions[?(@.type=='Ready')].status",type="string",description="When 'True', the most recent reconcile of the resource succeeded"
// +kubebuilder:printcolumn:name="Status",JSONPath=".status.conditions[?(@.type=='Ready')].reason",type="string",description="The reason for the value in 'Ready'"
// +kubebuilder:printcolumn:name="Status Age",JSONPath=".status.conditions[?(@.type=='Ready')].lastTransitionTime",type="date",description="The last transition time for the value in 'Status'"

// ComputeURLMap is the Schema for the compute API
// +k8s:openapi-gen=true
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/default-controller=direct"
type ComputeURLMap struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ComputeURLMapSpec   `json:"spec,omitempty"`
	Status ComputeURLMapStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ComputeURLMapList contains a list of ComputeURLMap
type ComputeURLMapList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ComputeURLMap `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ComputeURLMap{}, &ComputeURLMapList{})
}
